
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by FuseSource Services Framework 2.5.0.fuse-7-061
 * 2013-01-23T23:53:39.913+05:30
 * Generated source version: 2.5.0.fuse-7-061
 */

@WebFault(name = "InvalidSObjectFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class InvalidSObjectFault extends Exception {
    
    private com.sforce.soap.enterprise.fault.InvalidSObjectFault invalidSObjectFault;

    public InvalidSObjectFault() {
        super();
    }
    
    public InvalidSObjectFault(String message) {
        super(message);
    }
    
    public InvalidSObjectFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSObjectFault(String message, com.sforce.soap.enterprise.fault.InvalidSObjectFault invalidSObjectFault) {
        super(message);
        this.invalidSObjectFault = invalidSObjectFault;
    }

    public InvalidSObjectFault(String message, com.sforce.soap.enterprise.fault.InvalidSObjectFault invalidSObjectFault, Throwable cause) {
        super(message, cause);
        this.invalidSObjectFault = invalidSObjectFault;
    }

    public com.sforce.soap.enterprise.fault.InvalidSObjectFault getFaultInfo() {
        return this.invalidSObjectFault;
    }
}
