
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by FuseSource Services Framework 2.5.0.fuse-7-061
 * 2013-01-23T23:53:39.905+05:30
 * Generated source version: 2.5.0.fuse-7-061
 */

@WebFault(name = "InvalidIdFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class InvalidIdFault extends Exception {
    
    private com.sforce.soap.enterprise.fault.InvalidIdFault invalidIdFault;

    public InvalidIdFault() {
        super();
    }
    
    public InvalidIdFault(String message) {
        super(message);
    }
    
    public InvalidIdFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidIdFault(String message, com.sforce.soap.enterprise.fault.InvalidIdFault invalidIdFault) {
        super(message);
        this.invalidIdFault = invalidIdFault;
    }

    public InvalidIdFault(String message, com.sforce.soap.enterprise.fault.InvalidIdFault invalidIdFault, Throwable cause) {
        super(message, cause);
        this.invalidIdFault = invalidIdFault;
    }

    public com.sforce.soap.enterprise.fault.InvalidIdFault getFaultInfo() {
        return this.invalidIdFault;
    }
}
